#!/bin/bash
HN="$1"
shift
if [[ "$HN" == "lassen" ]] ; then
    ssh -t lassen env WD="$(pwd)" ~/scikit-optimize/autotune/omp-example/3mm/fix_env bsub -nnodes 1 -Is -q pbatch -W 40 "$@"
#could add differen machines in here

else # assume current machine for now
    srun -t 20 ~/scikit-optimize/autotune/omp-example/3mm/fix_env "$@"
fi
